### ISSUE TITLE
Extraction fail

### ISSUE THREAD

**Issue by mimol91** [xsolve-pl/xsolve-feat#23]
While trying to fetch from master branch downloaded zip has folder named `mimol91-graphql-demo-7be6482` and application try to move `mimol91-graphql-demo-7be6482099df857868614996a6e7103ecb17ca1e` dir

How to recreate
```
curl -s -H "Authorization: token SECRET_TOKEN" -L https://api.github.com/repos/mimol91/graphql-demo/zipball/7be6482099df857868614996a6e7103ecb17ca1e > 7be6482099df857868614996a6e7103ecb17ca1e.zip  
```

**Comment by malef** [comment]
Fixed.
