### ISSUE TITLE
Assign only free ports

### ISSUE THREAD

**Issue by Kryniol** [xsolve-pl/xsolve-feat#25]
When the Node app is restarted, it starts to assign ports already taken by other build instances. It should firstly check whether particular port has not been taken yet.

**Comment by malef** [comment]
@Kryniol How would you approach this? Should we keep the list of ports that are already taken in Mongo, or in some file locally? Or should something like `netstat` be used to examine if port is in use?

**Comment by Kryniol** [comment]
I'm working on the easiest possible solution so just to check whether a port is free or not, using https://github.com/indexzero/node-portfinder for that purpose. WDYT?

**Comment by malef** [comment]
Looks good :+1:
