### ISSUE TITLE
Allow multiple docker-compose.yml files

### ISSUE THREAD

**Issue by IonBazan** [xsolve-pl/xsolve-feat#36]
We should allow users to define multiple `docker-compose.yml` files to override settings/services/volumes. This is usually done using following syntax:

`docker-compose -f docker-compose.yml -f docker-compose.prod.yml` [docs](https://docs.docker.com/compose/extends/#example-use-case)

or setting [COMPOSE_FILE](https://docs.docker.com/compose/reference/envvars/#COMPOSE_FILE) environment variable in `.env`.

**Comment by malef** [comment]
We've discussed this and it seems to be a very good idea - it will introduce a possibility to handle multiple environments with minimal amount of repetitions in compose files.

It can also be used as a replacement for `extends` (https://docs.docker.com/compose/compose-file/compose-file-v2/#extends) which doesn't require any specific handling in Feat.

**Comment by malef** [comment]
Addressed in https://github.com/xsolve-pl/xsolve-feat/pull/41
