### ISSUE TITLE
Hardcoded API URLs

### ISSUE THREAD

**Issue by Kryniol** [xsolve-pl/xsolve-feat#6]
In the files listed below the API URL is hardcoded to `http://localhost:3000`, base URL should be moved to some kind of configuration:

- `client/src/app/build-definition/repository/build-definition-repository.service.ts`
- `client/src/app/build-instance/repository/build-instance-repository.service.ts`
- `client/src/app/project/repository/project-repository.service.ts`

**Comment by malef** [comment]
I need to find out how to provide configuration upon build in Angular 2, so this may take me a day or two.

**Comment by mimol91** [comment]
Probably angular2 use webpack.
Maybe https://webpack.js.org/plugins/define-plugin/ will be suitable?

**Comment by malef** [comment]
Done in `master` branch (work in progress).
